name: Select target action
description: Configure the matrix job directory in GitHub Label
branding:
  icon: git-pull-request
  color: blue

inputs:
  config_file:
    description: 'config file path'
    required: false
    default: '.deploy_target.json'
  token:
    default: "${{ github.token }}"
    required: false
    description: "GITHUB_TOKEN"

outputs:
  targets:
    description: "List of working directories"
    value: ${{ steps.generate_matrix.outputs.targets }}

runs:
  using: "composite"
  steps:
    - name: Run ci-info
      uses: ponkio-o/select-target-action/ci-info@main
      with:
        token: ${{ inputs.token }}

    - name: Generate matrix
      id: generate_matrix
      uses: ponkio-o/select-target-action/generate-matrix@main
      with:
        config_file: ${{ inputs.config_file }}
