name: tagpr

on:
  push:
    branches: ["main"]

jobs:
  tagpr:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1.9.3
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Install aqua
        uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.25.2

      - name: Run tagpr
        run: tagpr
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
