name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'generate-matrix/.nvmrc'

      - name: Run test
        working-directory: generate-matrix
        run: |
          npm install
          npm ci
          npm test
